name: AuctionSystem
main: cc.nukkit.myzness.auction.Main
version: 1.3.0
api: [1.0.9]
author: 眠悠子Myzness
softdepend:
  - EconomyAPI
loadbefore:
  - EconomyAPI
description: 拍卖系统
website: https://bbs.nukkit-mot.com

permissions:
commands:
  auction:
    description: 拍卖系统
    usage: /auction <sell|join|cancel> [arg]